module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/__tests__'],
  testMatch: ['**/__tests__/**/*.test.ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  moduleFileExtensions: ['ts', 'js', 'json'],
  clearMocks: true,
  collectCoverage: true,
  coverageDirectory: 'coverage',
  coveragePathIgnorePatterns: ['/node_modules/'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@utils/(.*)$': '<rootDir>/src/utils/$1',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@sessions/(.*)$': '<rootDir>/src/sessions/$1',
    '^@git/(.*)$': '<rootDir>/src/git/$1',
    '^@UI/(.*)$': '<rootDir>/src/UI/$1',
    '^@commandsMaps/(.*)$': '<rootDir>/src/commandsMaps/$1',
    '^@helpers/(.*)$': '<rootDir>/src/helpers/$1',
    '^@system/(.*)$': '<rootDir>/src/system/$1',
    '^@filePaths$': '<rootDir>/src/filePaths.ts',
  },
};
