name: Test
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout and clone repository
              uses: actions/checkout@v4.1.1

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "23.8"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm t
